// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A discovered host on the LAN.
class HostInfo {
  final String name;
  final String address;
  final int port;

  const HostInfo({
    required this.name,
    required this.address,
    required this.port,
  });

  @override
  int get hashCode => name.hashCode ^ address.hashCode ^ port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          address == other.address &&
          port == other.port;
}
