// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/audio.dart';
import 'api/library.dart';
import 'api/network.dart';
import 'api/simple.dart';
import 'api/system.dart';
import 'dart:async';
import 'dart:convert';
import 'db/browse.dart';
import 'db/playlists.dart';
import 'db/tracks.dart';
import 'frb_generated.dart';
import 'net/discovery.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlbumRow dco_decode_album_row(dynamic raw);

  @protected
  ArtistRow dco_decode_artist_row(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  GenreRow dco_decode_genre_row(dynamic raw);

  @protected
  HostInfo dco_decode_host_info(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<AlbumRow> dco_decode_list_album_row(dynamic raw);

  @protected
  List<ArtistRow> dco_decode_list_artist_row(dynamic raw);

  @protected
  List<GenreRow> dco_decode_list_genre_row(dynamic raw);

  @protected
  List<HostInfo> dco_decode_list_host_info(dynamic raw);

  @protected
  List<PlaylistRow> dco_decode_list_playlist_row(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TrackRow> dco_decode_list_track_row(dynamic raw);

  @protected
  List<YearRow> dco_decode_list_year_row(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  PlaylistRow dco_decode_playlist_row(dynamic raw);

  @protected
  ScanReport dco_decode_scan_report(dynamic raw);

  @protected
  TrackRow dco_decode_track_row(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  YearRow dco_decode_year_row(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlbumRow sse_decode_album_row(SseDeserializer deserializer);

  @protected
  ArtistRow sse_decode_artist_row(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  GenreRow sse_decode_genre_row(SseDeserializer deserializer);

  @protected
  HostInfo sse_decode_host_info(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<AlbumRow> sse_decode_list_album_row(SseDeserializer deserializer);

  @protected
  List<ArtistRow> sse_decode_list_artist_row(SseDeserializer deserializer);

  @protected
  List<GenreRow> sse_decode_list_genre_row(SseDeserializer deserializer);

  @protected
  List<HostInfo> sse_decode_list_host_info(SseDeserializer deserializer);

  @protected
  List<PlaylistRow> sse_decode_list_playlist_row(SseDeserializer deserializer);

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TrackRow> sse_decode_list_track_row(SseDeserializer deserializer);

  @protected
  List<YearRow> sse_decode_list_year_row(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  PlaylistRow sse_decode_playlist_row(SseDeserializer deserializer);

  @protected
  ScanReport sse_decode_scan_report(SseDeserializer deserializer);

  @protected
  TrackRow sse_decode_track_row(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  YearRow sse_decode_year_row(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_album_row(AlbumRow self, SseSerializer serializer);

  @protected
  void sse_encode_artist_row(ArtistRow self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_genre_row(GenreRow self, SseSerializer serializer);

  @protected
  void sse_encode_host_info(HostInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_album_row(List<AlbumRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_artist_row(
    List<ArtistRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_genre_row(List<GenreRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_host_info(List<HostInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_playlist_row(
    List<PlaylistRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track_row(List<TrackRow> self, SseSerializer serializer);

  @protected
  void sse_encode_list_year_row(List<YearRow> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_row(PlaylistRow self, SseSerializer serializer);

  @protected
  void sse_encode_scan_report(ScanReport self, SseSerializer serializer);

  @protected
  void sse_encode_track_row(TrackRow self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_year_row(YearRow self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
