// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AlbumRow {
  final PlatformInt64 id;
  final String title;
  final String artist;
  final PlatformInt64? year;
  final PlatformInt64 trackCount;

  const AlbumRow({
    required this.id,
    required this.title,
    required this.artist,
    this.year,
    required this.trackCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      year.hashCode ^
      trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          year == other.year &&
          trackCount == other.trackCount;
}

class ArtistRow {
  final PlatformInt64 id;
  final String name;
  final PlatformInt64 albumCount;
  final PlatformInt64 trackCount;

  const ArtistRow({
    required this.id,
    required this.name,
    required this.albumCount,
    required this.trackCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ albumCount.hashCode ^ trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          albumCount == other.albumCount &&
          trackCount == other.trackCount;
}

class GenreRow {
  final PlatformInt64 id;
  final String name;
  final PlatformInt64 trackCount;

  const GenreRow({
    required this.id,
    required this.name,
    required this.trackCount,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GenreRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          trackCount == other.trackCount;
}

class YearRow {
  final PlatformInt64 year;
  final PlatformInt64 trackCount;

  const YearRow({required this.year, required this.trackCount});

  @override
  int get hashCode => year.hashCode ^ trackCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is YearRow &&
          runtimeType == other.runtimeType &&
          year == other.year &&
          trackCount == other.trackCount;
}
