// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class EqPresetRow {
  final PlatformInt64 id;
  final String name;
  final Float64List bands;
  final double preamp;
  final bool builtin;

  const EqPresetRow({
    required this.id,
    required this.name,
    required this.bands,
    required this.preamp,
    required this.builtin,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      bands.hashCode ^
      preamp.hashCode ^
      builtin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqPresetRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          bands == other.bands &&
          preamp == other.preamp &&
          builtin == other.builtin;
}
