// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FolderRow {
  final PlatformInt64 id;
  final String path;
  final bool isWatched;
  final PlatformInt64 addedAt;

  const FolderRow({
    required this.id,
    required this.path,
    required this.isWatched,
    required this.addedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^ path.hashCode ^ isWatched.hashCode ^ addedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          isWatched == other.isWatched &&
          addedAt == other.addedAt;
}
