// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PlaylistRow {
  final PlatformInt64 id;
  final String name;
  final PlatformInt64 trackCount;
  final PlatformInt64 sortOrder;
  final PlatformInt64 createdAt;
  final PlatformInt64 updatedAt;

  const PlaylistRow({
    required this.id,
    required this.name,
    required this.trackCount,
    required this.sortOrder,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      trackCount.hashCode ^
      sortOrder.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          trackCount == other.trackCount &&
          sortOrder == other.sortOrder &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}
