// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A share as shown to the host UI. The `pin_hash` is never exposed; `has_pin`
/// only signals whether a PIN is set.
class ShareRow {
  final PlatformInt64 id;

  /// `None` == the whole library.
  final PlatformInt64? playlistId;

  /// Display label: the playlist name, or "Whole library" for the library share.
  final String label;

  /// `"stream"` | `"stream_download"`.
  final String permission;

  /// `"open"` | `"pin"` | `"approved"`.
  final String mode;
  final bool hasPin;
  final bool enabled;

  const ShareRow({
    required this.id,
    this.playlistId,
    required this.label,
    required this.permission,
    required this.mode,
    required this.hasPin,
    required this.enabled,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      playlistId.hashCode ^
      label.hashCode ^
      permission.hashCode ^
      mode.hashCode ^
      hasPin.hashCode ^
      enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          playlistId == other.playlistId &&
          label == other.label &&
          permission == other.permission &&
          mode == other.mode &&
          hasPin == other.hasPin &&
          enabled == other.enabled;
}
