// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SmartPlaylistRow {
  final PlatformInt64 id;
  final String name;
  final String ruleJson;
  final PlatformInt64? limitN;
  final PlatformInt64 updatedAt;

  const SmartPlaylistRow({
    required this.id,
    required this.name,
    required this.ruleJson,
    this.limitN,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      ruleJson.hashCode ^
      limitN.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SmartPlaylistRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          ruleJson == other.ruleJson &&
          limitN == other.limitN &&
          updatedAt == other.updatedAt;
}
