// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A track row shaped for display lists (artist/album flattened to text).
class TrackRow {
  final PlatformInt64 id;
  final String title;
  final String artist;
  final String album;
  final PlatformInt64? albumId;
  final PlatformInt64 durationMs;
  final PlatformInt64? year;
  final PlatformInt64 rating;
  final PlatformInt64 playedCount;

  const TrackRow({
    required this.id,
    required this.title,
    required this.artist,
    required this.album,
    this.albumId,
    required this.durationMs,
    this.year,
    required this.rating,
    required this.playedCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumId.hashCode ^
      durationMs.hashCode ^
      year.hashCode ^
      rating.hashCode ^
      playedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumId == other.albumId &&
          durationMs == other.durationMs &&
          year == other.year &&
          rating == other.rating &&
          playedCount == other.playedCount;
}
