// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A recent transfer, joined with the track title for display.
class TransferRow {
  final String peer;
  final PlatformInt64? trackId;
  final String title;

  /// `"stream"` | `"download"`.
  final String kind;
  final PlatformInt64 at;

  const TransferRow({
    required this.peer,
    this.trackId,
    required this.title,
    required this.kind,
    required this.at,
  });

  @override
  int get hashCode =>
      peer.hashCode ^
      trackId.hashCode ^
      title.hashCode ^
      kind.hashCode ^
      at.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransferRow &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          trackId == other.trackId &&
          title == other.title &&
          kind == other.kind &&
          at == other.at;
}
