// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`

/// Load `path` and start playing it (replacing anything current).
void audioPlayPath({required String path}) =>
    RustLib.instance.api.crateApiAudioAudioPlayPath(path: path);

void audioPause() => RustLib.instance.api.crateApiAudioAudioPause();

void audioResume() => RustLib.instance.api.crateApiAudioAudioResume();

void audioStop() => RustLib.instance.api.crateApiAudioAudioStop();

void audioSeekMs({required PlatformInt64 ms}) =>
    RustLib.instance.api.crateApiAudioAudioSeekMs(ms: ms);

/// Volume 0.0–2.0 (1.0 = unity).
void audioSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiAudioAudioSetVolume(volume: volume);

/// Playback speed 0.25–4.0 (1.0 = normal). NOTE: rodio's speed also shifts
/// pitch; pitch-preserving speed arrives with the P4 custom engine.
void audioSetSpeed({required double speed}) =>
    RustLib.instance.api.crateApiAudioAudioSetSpeed(speed: speed);

/// 10-band graphic EQ, using ISO octave centers from 31 Hz to 16 kHz.
/// `gains` must contain exactly 10 dB values. Values are clamped by the engine
/// to -12..12 dB; `preamp_db` is clamped to -15..15 dB.
void audioSetEq({required List<double> gains, required double preampDb}) =>
    RustLib.instance.api.crateApiAudioAudioSetEq(
      gains: gains,
      preampDb: preampDb,
    );

PlatformInt64 audioPositionMs() =>
    RustLib.instance.api.crateApiAudioAudioPositionMs();

PlatformInt64 audioDurationMs() =>
    RustLib.instance.api.crateApiAudioAudioDurationMs();

bool audioIsPlaying() => RustLib.instance.api.crateApiAudioAudioIsPlaying();

String? audioLastError() => RustLib.instance.api.crateApiAudioAudioLastError();
