// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`

/// Load `path` and start playing it (replacing anything current).
void audioPlayPath({required String path}) =>
    RustLib.instance.api.crateApiAudioAudioPlayPath(path: path);

void audioPause() => RustLib.instance.api.crateApiAudioAudioPause();

void audioResume() => RustLib.instance.api.crateApiAudioAudioResume();

void audioStop() => RustLib.instance.api.crateApiAudioAudioStop();

void audioSeekMs({required PlatformInt64 ms}) =>
    RustLib.instance.api.crateApiAudioAudioSeekMs(ms: ms);

/// Volume 0.0–2.0 (1.0 = unity).
void audioSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiAudioAudioSetVolume(volume: volume);

/// Playback speed; the engine clamps to 0.5–2.0 (1.0 = normal). On Linux/macOS
/// this is pitch-preserving via Signalsmith Stretch; on Windows (MSVC) the
/// stretch stage is disabled and speed falls back to rodio's pitch-shifting
/// resample.
void audioSetSpeed({required double speed}) =>
    RustLib.instance.api.crateApiAudioAudioSetSpeed(speed: speed);

/// Crossfade duration between tracks, in seconds (0–12; 0 disables — the default).
void audioSetCrossfade({required double secs}) =>
    RustLib.instance.api.crateApiAudioAudioSetCrossfade(secs: secs);

/// Latest Now-Playing visualizer spectrum: `bands` log-spaced magnitudes, each
/// roughly 0..1. Cheap (one cached 1024-pt FFT); poll at the UI frame rate.
/// All-zero when idle, and on Android (no desktop engine).
Float32List audioSpectrum({required int bands}) =>
    RustLib.instance.api.crateApiAudioAudioSpectrum(bands: bands);

/// 10-band graphic EQ, using ISO octave centers from 31 Hz to 16 kHz.
/// `gains` must contain exactly 10 dB values. Values are clamped by the engine
/// to -12..12 dB; `preamp_db` is clamped to -15..15 dB.
void audioSetEq({required List<double> gains, required double preampDb}) =>
    RustLib.instance.api.crateApiAudioAudioSetEq(
      gains: gains,
      preampDb: preampDb,
    );

Future<List<OutputDeviceRow>> audioOutputDevices() =>
    RustLib.instance.api.crateApiAudioAudioOutputDevices();

Future<void> audioSetOutputDevice({String? deviceId}) =>
    RustLib.instance.api.crateApiAudioAudioSetOutputDevice(deviceId: deviceId);

/// Stereo width: 0.0 = mono, 1.0 = unchanged, 2.0 = widened.
void audioSetStereoWidth({required double width}) =>
    RustLib.instance.api.crateApiAudioAudioSetStereoWidth(width: width);

PlatformInt64 audioPositionMs() =>
    RustLib.instance.api.crateApiAudioAudioPositionMs();

PlatformInt64 audioDurationMs() =>
    RustLib.instance.api.crateApiAudioAudioDurationMs();

bool audioIsPlaying() => RustLib.instance.api.crateApiAudioAudioIsPlaying();

String? audioLastError() => RustLib.instance.api.crateApiAudioAudioLastError();

class OutputDeviceRow {
  final String id;
  final String name;
  final bool isDefault;

  const OutputDeviceRow({
    required this.id,
    required this.name,
    required this.isDefault,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ isDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutputDeviceRow &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          isDefault == other.isDefault;
}
