// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`

/// Load `path` and start playing it (replacing anything current).
void audioPlayPath({required String path}) =>
    RustLib.instance.api.crateApiAudioAudioPlayPath(path: path);

void audioPause() => RustLib.instance.api.crateApiAudioAudioPause();

void audioResume() => RustLib.instance.api.crateApiAudioAudioResume();

void audioStop() => RustLib.instance.api.crateApiAudioAudioStop();

void audioSeekMs({required PlatformInt64 ms}) =>
    RustLib.instance.api.crateApiAudioAudioSeekMs(ms: ms);

/// Volume 0.0–2.0 (1.0 = unity).
void audioSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiAudioAudioSetVolume(volume: volume);

PlatformInt64 audioPositionMs() =>
    RustLib.instance.api.crateApiAudioAudioPositionMs();

PlatformInt64 audioDurationMs() =>
    RustLib.instance.api.crateApiAudioAudioDurationMs();

bool audioIsPlaying() => RustLib.instance.api.crateApiAudioAudioIsPlaying();

String? audioLastError() => RustLib.instance.api.crateApiAudioAudioLastError();
