// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db/tracks.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `now_ms`, `with_db`

/// Open (creating if needed) the library database at `db_path`.
Future<void> libraryOpen({required String dbPath}) =>
    RustLib.instance.api.crateApiLibraryLibraryOpen(dbPath: dbPath);

/// Recursively scan `path`, importing new/changed audio files. Returns counts.
Future<ScanReport> libraryScan({required String path}) =>
    RustLib.instance.api.crateApiLibraryLibraryScan(path: path);

/// Browse all songs ordered by title, paginated.
Future<List<TrackRow>> libraryBrowseSongs({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiLibraryLibraryBrowseSongs(
  limit: limit,
  offset: offset,
);

/// Fuzzy search across title/artist/album/genre.
Future<List<TrackRow>> librarySearch({
  required String query,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLibraryLibrarySearch(
  query: query,
  limit: limit,
);

/// Total track count.
Future<PlatformInt64> libraryTrackCount() =>
    RustLib.instance.api.crateApiLibraryLibraryTrackCount();

/// Result of a folder scan.
class ScanReport {
  final int added;
  final int updated;
  final int skipped;
  final int errors;

  const ScanReport({
    required this.added,
    required this.updated,
    required this.skipped,
    required this.errors,
  });

  @override
  int get hashCode =>
      added.hashCode ^ updated.hashCode ^ skipped.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanReport &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          updated == other.updated &&
          skipped == other.skipped &&
          errors == other.errors;
}
