// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db/browse.dart';
import '../db/eq_presets.dart';
import '../db/folders.dart';
import '../db/playlists.dart';
import '../db/smart.dart';
import '../db/tracks.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `export_playlist_file`, `import_playlist_file`, `now_ms`, `with_db`

/// Open (creating if needed) the library database at `db_path`.
Future<void> libraryOpen({required String dbPath}) =>
    RustLib.instance.api.crateApiLibraryLibraryOpen(dbPath: dbPath);

/// Recursively scan `path`, importing new/changed audio files, and remember it
/// as a library folder. Returns counts.
Future<ScanReport> libraryScan({required String path}) =>
    RustLib.instance.api.crateApiLibraryLibraryScan(path: path);

/// The folders the user has scanned (library sources).
Future<List<FolderRow>> libraryFolders() =>
    RustLib.instance.api.crateApiLibraryLibraryFolders();

/// Forget a library folder and remove the tracks under it.
Future<void> libraryRemoveFolder({required PlatformInt64 folderId}) =>
    RustLib.instance.api.crateApiLibraryLibraryRemoveFolder(folderId: folderId);

/// Re-scan every known folder: import new/changed files and prune tracks whose
/// files have been deleted (skipping inaccessible/empty roots). Aggregate counts.
Future<ScanReport> libraryRescanAll() =>
    RustLib.instance.api.crateApiLibraryLibraryRescanAll();

/// Browse all songs ordered by title, paginated.
Future<List<TrackRow>> libraryBrowseSongs({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiLibraryLibraryBrowseSongs(
  limit: limit,
  offset: offset,
);

/// Fuzzy search across title/artist/album/genre.
Future<List<TrackRow>> librarySearch({
  required String query,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLibraryLibrarySearch(
  query: query,
  limit: limit,
);

/// Fetch a single track by id (`None` if it no longer exists).
Future<TrackRow?> libraryTrackById({required PlatformInt64 trackId}) =>
    RustLib.instance.api.crateApiLibraryLibraryTrackById(trackId: trackId);

/// Read the current tag fields from a track's file (for the metadata editor).
Future<TrackTags> libraryTrackTags({required PlatformInt64 trackId}) =>
    RustLib.instance.api.crateApiLibraryLibraryTrackTags(trackId: trackId);

/// Write edited tags back to the track's file, then re-read it into the
/// library. Returns the refreshed row. `artist`/`genre` accept `;`-separated
/// multi-values; empty strings clear the field.
Future<TrackRow> libraryUpdateTags({
  required PlatformInt64 trackId,
  required String title,
  required String artist,
  required String album,
  required String albumArtist,
  required String genre,
  PlatformInt64? year,
  PlatformInt64? trackNo,
}) => RustLib.instance.api.crateApiLibraryLibraryUpdateTags(
  trackId: trackId,
  title: title,
  artist: artist,
  album: album,
  albumArtist: albumArtist,
  genre: genre,
  year: year,
  trackNo: trackNo,
);

/// Read a persisted setting, or `None` if unset.
Future<String?> settingsGet({required String key}) =>
    RustLib.instance.api.crateApiLibrarySettingsGet(key: key);

/// Write (upsert) a persisted setting.
Future<void> settingsSet({required String key, required String value}) =>
    RustLib.instance.api.crateApiLibrarySettingsSet(key: key, value: value);

/// Delete a persisted setting (no-op if absent).
Future<void> settingsDelete({required String key}) =>
    RustLib.instance.api.crateApiLibrarySettingsDelete(key: key);

Future<List<EqPresetRow>> eqPresetList() =>
    RustLib.instance.api.crateApiLibraryEqPresetList();

Future<PlatformInt64> eqPresetCreate({
  required String name,
  required List<double> bands,
  required double preamp,
}) => RustLib.instance.api.crateApiLibraryEqPresetCreate(
  name: name,
  bands: bands,
  preamp: preamp,
);

Future<void> eqPresetUpdate({
  required PlatformInt64 presetId,
  required String name,
  required List<double> bands,
  required double preamp,
}) => RustLib.instance.api.crateApiLibraryEqPresetUpdate(
  presetId: presetId,
  name: name,
  bands: bands,
  preamp: preamp,
);

Future<void> eqPresetDelete({required PlatformInt64 presetId}) =>
    RustLib.instance.api.crateApiLibraryEqPresetDelete(presetId: presetId);

Future<List<AlbumRow>> libraryBrowseAlbums({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiLibraryLibraryBrowseAlbums(
  limit: limit,
  offset: offset,
);

Future<List<ArtistRow>> libraryBrowseArtists() =>
    RustLib.instance.api.crateApiLibraryLibraryBrowseArtists();

Future<List<GenreRow>> libraryBrowseGenres() =>
    RustLib.instance.api.crateApiLibraryLibraryBrowseGenres();

Future<List<YearRow>> libraryBrowseYears() =>
    RustLib.instance.api.crateApiLibraryLibraryBrowseYears();

Future<List<TrackRow>> libraryAlbumTracks({required PlatformInt64 albumId}) =>
    RustLib.instance.api.crateApiLibraryLibraryAlbumTracks(albumId: albumId);

Future<List<TrackRow>> libraryArtistTracks({required PlatformInt64 artistId}) =>
    RustLib.instance.api.crateApiLibraryLibraryArtistTracks(artistId: artistId);

Future<List<TrackRow>> libraryGenreTracks({required PlatformInt64 genreId}) =>
    RustLib.instance.api.crateApiLibraryLibraryGenreTracks(genreId: genreId);

Future<List<TrackRow>> libraryTracksByYear({required PlatformInt64 year}) =>
    RustLib.instance.api.crateApiLibraryLibraryTracksByYear(year: year);

Future<List<TrackRow>> libraryRecentlyAdded({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiLibraryLibraryRecentlyAdded(limit: limit);

/// Total track count.
Future<PlatformInt64> libraryTrackCount() =>
    RustLib.instance.api.crateApiLibraryLibraryTrackCount();

Future<List<PlaylistRow>> playlistList() =>
    RustLib.instance.api.crateApiLibraryPlaylistList();

Future<PlatformInt64> playlistCreate({required String name}) =>
    RustLib.instance.api.crateApiLibraryPlaylistCreate(name: name);

Future<void> playlistRename({
  required PlatformInt64 playlistId,
  required String name,
}) => RustLib.instance.api.crateApiLibraryPlaylistRename(
  playlistId: playlistId,
  name: name,
);

Future<void> playlistDelete({required PlatformInt64 playlistId}) =>
    RustLib.instance.api.crateApiLibraryPlaylistDelete(playlistId: playlistId);

Future<PlatformInt64> playlistDuplicate({
  required PlatformInt64 playlistId,
  required String name,
}) => RustLib.instance.api.crateApiLibraryPlaylistDuplicate(
  playlistId: playlistId,
  name: name,
);

Future<List<TrackRow>> playlistTracks({required PlatformInt64 playlistId}) =>
    RustLib.instance.api.crateApiLibraryPlaylistTracks(playlistId: playlistId);

Future<void> playlistAddTracks({
  required PlatformInt64 playlistId,
  required Int64List trackIds,
}) => RustLib.instance.api.crateApiLibraryPlaylistAddTracks(
  playlistId: playlistId,
  trackIds: trackIds,
);

Future<void> playlistRemovePosition({
  required PlatformInt64 playlistId,
  required PlatformInt64 position,
}) => RustLib.instance.api.crateApiLibraryPlaylistRemovePosition(
  playlistId: playlistId,
  position: position,
);

Future<void> playlistReorderTracks({
  required PlatformInt64 playlistId,
  required Int64List trackIds,
}) => RustLib.instance.api.crateApiLibraryPlaylistReorderTracks(
  playlistId: playlistId,
  trackIds: trackIds,
);

/// Import an `.m3u`/`.m3u8`/`.pls` file as a new playlist (named after the
/// file). Path entries are matched against the library by normalized path;
/// unmatched entries are skipped and reported.
Future<PlaylistImportReport> playlistImport({required String filePath}) =>
    RustLib.instance.api.crateApiLibraryPlaylistImport(filePath: filePath);

/// Export a playlist to `file_path`. Format is chosen by the file extension
/// (`.pls` → PLS, otherwise extended M3U).
Future<void> playlistExport({
  required PlatformInt64 playlistId,
  required String filePath,
}) => RustLib.instance.api.crateApiLibraryPlaylistExport(
  playlistId: playlistId,
  filePath: filePath,
);

Future<List<SmartPlaylistRow>> smartPlaylistList() =>
    RustLib.instance.api.crateApiLibrarySmartPlaylistList();

/// Create a smart playlist after validating the rule JSON compiles.
Future<PlatformInt64> smartPlaylistCreate({
  required String name,
  required String ruleJson,
  PlatformInt64? limitN,
}) => RustLib.instance.api.crateApiLibrarySmartPlaylistCreate(
  name: name,
  ruleJson: ruleJson,
  limitN: limitN,
);

Future<void> smartPlaylistUpdate({
  required PlatformInt64 smartId,
  required String name,
  required String ruleJson,
  PlatformInt64? limitN,
}) => RustLib.instance.api.crateApiLibrarySmartPlaylistUpdate(
  smartId: smartId,
  name: name,
  ruleJson: ruleJson,
  limitN: limitN,
);

Future<void> smartPlaylistDelete({required PlatformInt64 smartId}) =>
    RustLib.instance.api.crateApiLibrarySmartPlaylistDelete(smartId: smartId);

/// Resolve a saved smart playlist to its current matching tracks.
Future<List<TrackRow>> smartPlaylistTracks({required PlatformInt64 smartId}) =>
    RustLib.instance.api.crateApiLibrarySmartPlaylistTracks(smartId: smartId);

/// Preview a rule set without saving it (for the rule builder UI).
Future<List<TrackRow>> smartPlaylistPreview({
  required String ruleJson,
  PlatformInt64? limitN,
}) => RustLib.instance.api.crateApiLibrarySmartPlaylistPreview(
  ruleJson: ruleJson,
  limitN: limitN,
);

/// Outcome of importing a playlist file.
class PlaylistImportReport {
  final PlatformInt64 playlistId;

  /// Entries matched to a library track (and added to the new playlist).
  final int matched;

  /// Total path entries found in the file.
  final int total;

  const PlaylistImportReport({
    required this.playlistId,
    required this.matched,
    required this.total,
  });

  @override
  int get hashCode => playlistId.hashCode ^ matched.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistImportReport &&
          runtimeType == other.runtimeType &&
          playlistId == other.playlistId &&
          matched == other.matched &&
          total == other.total;
}

/// Result of a folder scan (or a rescan-all).
class ScanReport {
  final int added;
  final int updated;
  final int skipped;
  final int errors;

  /// Tracks pruned because their files no longer exist (rescan-all only).
  final int removed;

  const ScanReport({
    required this.added,
    required this.updated,
    required this.skipped,
    required this.errors,
    required this.removed,
  });

  @override
  int get hashCode =>
      added.hashCode ^
      updated.hashCode ^
      skipped.hashCode ^
      errors.hashCode ^
      removed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanReport &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          updated == other.updated &&
          skipped == other.skipped &&
          errors == other.errors &&
          removed == other.removed;
}

/// All editable tag fields for a track (read fresh from the file, so the editor
/// can prefill every field and not clobber ones absent from [`TrackRow`]).
class TrackTags {
  final String title;
  final String artist;
  final String album;
  final String albumArtist;
  final String genre;
  final PlatformInt64? year;
  final PlatformInt64? trackNo;

  const TrackTags({
    required this.title,
    required this.artist,
    required this.album,
    required this.albumArtist,
    required this.genre,
    this.year,
    this.trackNo,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      genre.hashCode ^
      year.hashCode ^
      trackNo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackTags &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          genre == other.genre &&
          year == other.year &&
          trackNo == other.trackNo;
}
