// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../db/browse.dart';
import '../db/playlists.dart';
import '../db/tracks.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `export_playlist_file`, `import_playlist_file`, `now_ms`, `with_db`

/// Open (creating if needed) the library database at `db_path`.
Future<void> libraryOpen({required String dbPath}) =>
    RustLib.instance.api.crateApiLibraryLibraryOpen(dbPath: dbPath);

/// Recursively scan `path`, importing new/changed audio files. Returns counts.
Future<ScanReport> libraryScan({required String path}) =>
    RustLib.instance.api.crateApiLibraryLibraryScan(path: path);

/// Browse all songs ordered by title, paginated.
Future<List<TrackRow>> libraryBrowseSongs({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiLibraryLibraryBrowseSongs(
  limit: limit,
  offset: offset,
);

/// Fuzzy search across title/artist/album/genre.
Future<List<TrackRow>> librarySearch({
  required String query,
  required PlatformInt64 limit,
}) => RustLib.instance.api.crateApiLibraryLibrarySearch(
  query: query,
  limit: limit,
);

/// Fetch a single track by id (`None` if it no longer exists).
Future<TrackRow?> libraryTrackById({required PlatformInt64 trackId}) =>
    RustLib.instance.api.crateApiLibraryLibraryTrackById(trackId: trackId);

/// Read a persisted setting, or `None` if unset.
Future<String?> settingsGet({required String key}) =>
    RustLib.instance.api.crateApiLibrarySettingsGet(key: key);

/// Write (upsert) a persisted setting.
Future<void> settingsSet({required String key, required String value}) =>
    RustLib.instance.api.crateApiLibrarySettingsSet(key: key, value: value);

/// Delete a persisted setting (no-op if absent).
Future<void> settingsDelete({required String key}) =>
    RustLib.instance.api.crateApiLibrarySettingsDelete(key: key);

Future<List<AlbumRow>> libraryBrowseAlbums({
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => RustLib.instance.api.crateApiLibraryLibraryBrowseAlbums(
  limit: limit,
  offset: offset,
);

Future<List<ArtistRow>> libraryBrowseArtists() =>
    RustLib.instance.api.crateApiLibraryLibraryBrowseArtists();

Future<List<GenreRow>> libraryBrowseGenres() =>
    RustLib.instance.api.crateApiLibraryLibraryBrowseGenres();

Future<List<YearRow>> libraryBrowseYears() =>
    RustLib.instance.api.crateApiLibraryLibraryBrowseYears();

Future<List<TrackRow>> libraryAlbumTracks({required PlatformInt64 albumId}) =>
    RustLib.instance.api.crateApiLibraryLibraryAlbumTracks(albumId: albumId);

Future<List<TrackRow>> libraryArtistTracks({required PlatformInt64 artistId}) =>
    RustLib.instance.api.crateApiLibraryLibraryArtistTracks(artistId: artistId);

Future<List<TrackRow>> libraryGenreTracks({required PlatformInt64 genreId}) =>
    RustLib.instance.api.crateApiLibraryLibraryGenreTracks(genreId: genreId);

Future<List<TrackRow>> libraryTracksByYear({required PlatformInt64 year}) =>
    RustLib.instance.api.crateApiLibraryLibraryTracksByYear(year: year);

Future<List<TrackRow>> libraryRecentlyAdded({required PlatformInt64 limit}) =>
    RustLib.instance.api.crateApiLibraryLibraryRecentlyAdded(limit: limit);

/// Total track count.
Future<PlatformInt64> libraryTrackCount() =>
    RustLib.instance.api.crateApiLibraryLibraryTrackCount();

Future<List<PlaylistRow>> playlistList() =>
    RustLib.instance.api.crateApiLibraryPlaylistList();

Future<PlatformInt64> playlistCreate({required String name}) =>
    RustLib.instance.api.crateApiLibraryPlaylistCreate(name: name);

Future<void> playlistRename({
  required PlatformInt64 playlistId,
  required String name,
}) => RustLib.instance.api.crateApiLibraryPlaylistRename(
  playlistId: playlistId,
  name: name,
);

Future<void> playlistDelete({required PlatformInt64 playlistId}) =>
    RustLib.instance.api.crateApiLibraryPlaylistDelete(playlistId: playlistId);

Future<PlatformInt64> playlistDuplicate({
  required PlatformInt64 playlistId,
  required String name,
}) => RustLib.instance.api.crateApiLibraryPlaylistDuplicate(
  playlistId: playlistId,
  name: name,
);

Future<List<TrackRow>> playlistTracks({required PlatformInt64 playlistId}) =>
    RustLib.instance.api.crateApiLibraryPlaylistTracks(playlistId: playlistId);

Future<void> playlistAddTracks({
  required PlatformInt64 playlistId,
  required Int64List trackIds,
}) => RustLib.instance.api.crateApiLibraryPlaylistAddTracks(
  playlistId: playlistId,
  trackIds: trackIds,
);

Future<void> playlistRemovePosition({
  required PlatformInt64 playlistId,
  required PlatformInt64 position,
}) => RustLib.instance.api.crateApiLibraryPlaylistRemovePosition(
  playlistId: playlistId,
  position: position,
);

Future<void> playlistReorderTracks({
  required PlatformInt64 playlistId,
  required Int64List trackIds,
}) => RustLib.instance.api.crateApiLibraryPlaylistReorderTracks(
  playlistId: playlistId,
  trackIds: trackIds,
);

/// Import an `.m3u`/`.m3u8`/`.pls` file as a new playlist (named after the
/// file). Path entries are matched against the library by normalized path;
/// unmatched entries are skipped and reported.
Future<PlaylistImportReport> playlistImport({required String filePath}) =>
    RustLib.instance.api.crateApiLibraryPlaylistImport(filePath: filePath);

/// Export a playlist to `file_path`. Format is chosen by the file extension
/// (`.pls` → PLS, otherwise extended M3U).
Future<void> playlistExport({
  required PlatformInt64 playlistId,
  required String filePath,
}) => RustLib.instance.api.crateApiLibraryPlaylistExport(
  playlistId: playlistId,
  filePath: filePath,
);

/// Outcome of importing a playlist file.
class PlaylistImportReport {
  final PlatformInt64 playlistId;

  /// Entries matched to a library track (and added to the new playlist).
  final int matched;

  /// Total path entries found in the file.
  final int total;

  const PlaylistImportReport({
    required this.playlistId,
    required this.matched,
    required this.total,
  });

  @override
  int get hashCode => playlistId.hashCode ^ matched.hashCode ^ total.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistImportReport &&
          runtimeType == other.runtimeType &&
          playlistId == other.playlistId &&
          matched == other.matched &&
          total == other.total;
}

/// Result of a folder scan.
class ScanReport {
  final int added;
  final int updated;
  final int skipped;
  final int errors;

  const ScanReport({
    required this.added,
    required this.updated,
    required this.skipped,
    required this.errors,
  });

  @override
  int get hashCode =>
      added.hashCode ^ updated.hashCode ^ skipped.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanReport &&
          runtimeType == other.runtimeType &&
          added == other.added &&
          updated == other.updated &&
          skipped == other.skipped &&
          errors == other.errors;
}
