// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../net/discovery.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Host`

/// Start sharing the library over the LAN: bind the HTTP server and advertise
/// via mDNS. Returns the port. Idempotent (returns the existing port).
Future<int> netStartHost({
  required String dbPath,
  required String displayName,
}) => RustLib.instance.api.crateApiNetworkNetStartHost(
  dbPath: dbPath,
  displayName: displayName,
);

/// Stop hosting (unadvertise + shut the server down).
Future<void> netStopHost() => RustLib.instance.api.crateApiNetworkNetStopHost();

Future<bool> netIsHosting() =>
    RustLib.instance.api.crateApiNetworkNetIsHosting();

Future<int?> netHostPort() => RustLib.instance.api.crateApiNetworkNetHostPort();

/// Browse the LAN for hosts for `timeout_ms`, returning the resolved peers.
Future<List<HostInfo>> netDiscover({required PlatformInt64 timeoutMs}) =>
    RustLib.instance.api.crateApiNetworkNetDiscover(timeoutMs: timeoutMs);
