// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Semantic version of `peerbeat_core` (matches the crate version).
Future<String> coreVersion() =>
    RustLib.instance.api.crateApiSystemCoreVersion();

/// A short banner the Dart side can show in About/Settings to confirm the native
/// core loaded and bridged successfully.
Future<String> coreBanner() => RustLib.instance.api.crateApiSystemCoreBanner();

/// Initialise process-wide state for the core: logging and the default crypto
/// provider for rustls. Safe to call multiple times.
Future<void> initCore() => RustLib.instance.api.crateApiSystemInitCore();
